version: '3.8'

services:
  liko-bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: liko-discord-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GUILD_ID=${GUILD_ID}
      - LOG_CHANNEL_ID=${LOG_CHANNEL_ID}
      - IGNORED_CHANNELS=${IGNORED_CHANNELS:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - WEBHOOK_URL=${WEBHOOK_URL:-}
    volumes:
      # Montage des logs pour persistance
      - ./logs:/app/logs
      # Montage optionnel pour les sauvegardes
      - ./backups:/app/backups
    ports:
      # Port pour les webhooks externes (optionnel)
      - "3000:3000"
    networks:
      - liko-network
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  liko-network:
    driver: bridge 