services:
  liko-bot:
    build:
      context: .
      dockerfile: Dockerfile.raspberry
    container_name: liko-discord-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=512
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GUILD_ID=${GUILD_ID}
      - STATUS_LOG_CHANNEL_ID=${STATUS_LOG_CHANNEL_ID}
      - MESSAGES_LOG_CHANNEL_ID=${MESSAGES_LOG_CHANNEL_ID}
      - FORBIDDEN_WORDS_LOG_CHANNEL_ID=${FORBIDDEN_WORDS_LOG_CHANNEL_ID}
      - MODERATION_LOG_CHANNEL_ID=${MODERATION_LOG_CHANNEL_ID}
      - IGNORED_CHANNELS=${IGNORED_CHANNELS:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOGS_PATH=${LOGS_PATH:-/app/logs}
    ports:
      - "8080:8080"
    volumes:
      # Montage des logs pour persistance (chemin configurable)
      - ${LOGS_PATH:-./logs}:/app/logs

    networks:
      - liko-network
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Optimisations pour Raspberry Pi (sans limites mémoire pour éviter les warnings)
    # Les limites mémoire sont désactivées car le kernel Raspberry Pi ne les supporte pas

networks:
  liko-network:
    driver: bridge 