version: '3.8'

services:
  liko-bot:
    build:
      context: .
      dockerfile: Dockerfile.raspberry
    container_name: liko-discord-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GUILD_ID=${GUILD_ID}
      - STATUS_LOG_CHANNEL_ID=${STATUS_LOG_CHANNEL_ID}
      - MESSAGES_LOG_CHANNEL_ID=${MESSAGES_LOG_CHANNEL_ID}
      - FORBIDDEN_WORDS_LOG_CHANNEL_ID=${FORBIDDEN_WORDS_LOG_CHANNEL_ID}
      - MODERATION_LOG_CHANNEL_ID=${MODERATION_LOG_CHANNEL_ID}
      - IGNORED_CHANNELS=${IGNORED_CHANNELS:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      # Montage des logs pour persistance
      - ./logs:/app/logs
      # Montage optionnel pour les sauvegardes
      - ./backups:/app/backups

    networks:
      - liko-network
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Optimisations pour Raspberry Pi
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  liko-network:
    driver: bridge 